#!/bin/bash

mkdir -p dist
rm -f dist/*.js
rollup --format es6 s_enum.js > dist/s_enum.es2015.js
rollup --format amd s_enum.js > dist/s_enum.amd.js
rollup --format cjs s_enum.js > dist/s_enum.cjs.js
#rollup --format umd s_enum.js > dist/s_enum.umd.js

